baseurl = "https://as4mo3.github.io/JohnGraceSuits/"
languageCode = "en"
title = "John Grace Suits"
theme = "vex-hugo"
publishDir = "docs"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = ["css/custom.css", "css/blog.css"]
  custom_scripts = ["https://unpkg.com/ionicons@4.2.4/dist/ionicons.js"]

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "John Grace Suits"
	link = ""
    [[params.navbar.menu]]
      link = ""
      text = "HOME"
    #[[params.navbar.menu]]
     # link = "/services"
     # text = "SERVICES"
	[[params.navbar.menu]]
      link = "/f1"
      text = "F1 DRIVER'S SHOW"
    [[params.navbar.menu]]
      link = "/contact"
      text = "CONTACT"
	[[params.navbar.menu]]
      link = "/faq"
      text = "FAQ"
	[[params.navbar.menu]]
		link = "/blog"
		text = "BLOG"
		
	
  # Header
  [params.header]
    title = "Believe in Technology, Make the Change"
    text = "John Grace Suits specializes in making suits that fit you. Through a combination of 3-D imaging, Artificial Intelligence, and our world-class tailors, we will make you the best suit you ever had."
    [params.header.image]
      path = "images/suit-1.jpg"
      alt = "Suit banner"
    [params.header.button]
      link = "/contact"
      text = "Reserve your consultation now"

  # Features
  [params.features]
    title = "Our Core Philosophy"
    [params.features.image]
      path = "images/suit.jpg"
      alt = "Suit"
    # Menu at the left of the image
    [[params.features.left]]
      icon = "tf-ion-bowtie"
      title = "Quality"
      text = "Using only the finest Italian fabrics, the premium lustre of a John Grace will last you a lifetime. "
    [[params.features.left]]
      icon = "tf-ion-ios-alarm-outline"
      title = "Smooth Touch"
      text = "We come to the comfort of your home for private appointments, saving you time."
    # Menu at the right of the image
    [[params.features.right]]
      icon = "tf-ion-ios-bell-outline"
      title = "Perfect Fit"
      text = "In 20 minutes, we take over 120 distinct measurements, including a 3-D scan, making your suit fit you exactly."
    [[params.features.right]]
      icon = "tf-ion-ios-cart-outline"
      title = "Easy Pricing"
      text = "Our team works quickly and efficiently, leading to much a much lower suit cost, without the need for any alterations."

  [params.promo]
    title = "John Grace suit's are stylish, contemporary and cut to perfection."  
    text = "Over the course of our years of experience, we have learned how to make the suit that fits YOU. Therefore, John Grace Suits is the best option for the modern gentleman, with our contemporary tailoring perfect for both men and women."
    [params.promo.image]
      path = "images/suit-2.png"
      alt = "Suit"

  [params.feature_list]
    title = "The Three Steps to a John Grace Suit"
    [[params.feature_list.items]]
      image = "images/planning.jpg"
	  alt = "planning"
      title = "Planning"
      text = "The first part of the process starts with planning, and choosing your type of suit. Our fashion consultants help you decide which fabric, cut, and style would fit you the best, and we make a working model for your suit."
      button_link = "/faq"
      button_text = "Learn More"
    [[params.feature_list.items]]
      image = "images/3-D print.jpg"
	  alt = "3-D print"
      title = "Measurement and 3-D Printing"
      text = "Our tailors then take your measurements with a 3-D camera, a process which takes less than 20 minutes. We then print the 3-D model in order to be able to fit your suit perfectly. This whole process takes less than two days, much faster than a traditional approach."
      button_link = "/faq"
      button_text = "Learn More"
	[[params.feature_list.items]]
      image = "images/Rack of Suits.png"
	  alt = "Rack of Suits"
      title = "Delivery and Precise Measurements"
      text = "Over the course of two weeks, we finish your suit and ship it off to you. Furthermore, if you choose to order more suits, we will not have to take any new measurements because we already have the 3-D model of your body."
      button_link = "/faq"
      button_text = "Learn More"

  [params.gallery]
    title = "Check Out Our Amazing Suits"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["showcase-1.png", "showcase-2.jpg", "showcase-3.jpg", "showcase-4.jpg", "showcase-5.jpg", "showcase-6.jpg", "showcase-7.png", "showcase-8.png"]

  [params.call_to_action]
    title = "Get Suit Updates"
    text = "Stay up to date"
    placeholder = "Your Email Address Here"
    button_text = "Subscribe"

  [params.testimonials]
    title = "Suit Reviews"
    [[params.testimonials.blocks]]
      text = "PLACEHOLDER lots and lots of PLACEHOLDER"
      name = "Placeholder Smith"
      position = "Placeholder, Placeholder Inc"
      image = "images/avatar.png"
	  alt = "Placeholder Smith"
    [[params.testimonials.blocks]]
      text = "PLACEHOLDER lots and lots of PLACEHOLDER"
      name = "Placeholder Smith"
      position = "Placeholder, Placeholder Inc"
      image = "images/avatar.png"
	  alt = "Placeholder Smith"
    [[params.testimonials.blocks]]
      text = "PLACEHOLDER lots and lots of PLACEHOLDER"
      name = "Placeholder Smith"
      position = "Placeholder, Placeholder Inc"
      image = "images/avatar.png"
	  alt = "Placeholder Smith"
    [params.testimonials.button]
      link = "/contact"
      text = "Get Your Suit Now"
	  
	
	[params.f1]
		title = "Singapore F1 Grand Prix Dressed by John Grace"
		image = "images/F1BW.webp"
		alt = "F1 Show"
		button_text = "Order Your Own Suit Now"
		link = "/contact"
		[[params.f1.images]]
			image = "images/f1-showcase1.webp"
			alt = "F1 Showcase 1"
		[[params.f1.images]]
			image = "images/f1-showcase4.webp"
			alt = "F1 Showcase 4"
		[[params.f1.images]]
			image = "images/f1-showcase3.webp"
			alt = "F1 Showcase 3"		
		[[params.f1.images]]
			image = "images/f1-showcase2.webp"
			alt = "F1 Showcase 2"
			
	[params.blog]
		date_format = "January 2, 2006"
	
	[params.widgets]
		categories = true
		tags = true
		search = false
	
	[Permalinks]
		blog = "/blog/:year/:month/:day/:filename/"

  [params.contact]
	email = "tosha7y@gmail.com"
	address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
	latitude = "-12.043333"
    longitude = "-77.028333"
	googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

  # Footer uses navbar data
