baseurl = "https://as4mo3.github.io/JohnGraceSuits/"
languageCode = "en"
title = "John Grace Suits"
theme = "vex-hugo"
publishDir = "docs"

googleAnalytics = "UA-122955127-1"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = ["css/custom.css", "css/blog.css", "//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"]
  custom_scripts = ["https://unpkg.com/ionicons@4.2.4/dist/ionicons.js", "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js", "//code.jquery.com/jquery-1.10.2.js", "//code.jquery.com/ui/1.11.4/jquery-ui.js", "/js/modal.js", "/js/modalTabs.js", "/js/formValidation.js"]

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "John Grace Suits"
	link = ""
    [[params.navbar.menu]]
      link = ""
      text = "HOME"
    #[[params.navbar.menu]]
     # link = "/services"
     # text = "SERVICES"
	[[params.navbar.menu]]
      link = "/f1"
      text = "F1 DRIVER'S SHOW"
  [[params.navbar.menu]]
    link = "/product"
    text = "SUITS"
    [[params.navbar.menu]]
      link = "/contact"
      text = "CONTACT"
	[[params.navbar.menu]]
      link = "/faq"
      text = "FAQ"
	[[params.navbar.menu]]
		link = "/blog"
		text = "BLOG"


  # Header
  [params.header]
    title = "Believe in Technology, Make the Change"
    text = "John Grace Suits specializes in making suits that fit you. Through a combination of 3-D imaging, Artificial Intelligence, and our world-class tailors, we will make you the best suit you ever had."
    [params.header.image]
      path = "images/suit-1.jpg"
      alt = "Suit banner"
    [params.header.button]
      link = "/contact"
      text = "Reserve your consultation now"

  # Features
  [params.features]
    title = "Our Core Philosophy"
    [params.features.image]
      path = "images/suit.jpg"
      alt = "Suit"
    # Menu at the left of the image
    [[params.features.left]]
      icon = "tf-ion-bowtie"
      title = "Quality"
      text = "Using only the finest Italian fabrics, the premium lustre of a John Grace will last you a lifetime. "
    [[params.features.left]]
      icon = "tf-ion-ios-alarm-outline"
      title = "Fast Action"
      text = "We come to the comfort of your home for private appointments, saving you time."
    # Menu at the right of the image
    [[params.features.right]]
      icon = "tf-ion-ios-bell-outline"
      title = "Perfect Fit"
      text = "In 20 minutes, we take over 120 distinct measurements, including a 3-D scan, making your suit fit you exactly."
    [[params.features.right]]
      icon = "tf-ion-ios-cart-outline"
      title = "Easy Pricing"
      text = "Our team works quickly and efficiently, leading to much a much lower suit cost, without the need for any alterations."

  [params.promo]
    title = "John Grace suits are stylish, contemporary and cut to perfection."
    text = "Over the course of our years of experience, we have learned how to make the suit that fits YOU. Therefore, John Grace Suits is the best option for the modern gentleman, with our contemporary tailoring perfect for both anyone, anywhere."
    [params.promo.image]
      path = "images/suit-2.png"
      alt = "Suit"

  [params.feature_list]
    title = "The Three Steps to a John Grace Suit"
    [[params.feature_list.items]]
      image = "images/planning.jpg"
	  alt = "planning"
      title = "Planning"
      text = "The first part of the process starts with planning, and choosing your type of suit. Our fashion consultants help you decide which fabric, cut, and style would fit you the best, and we make a working model for your suit."
      button_link = "/faq"
      button_text = "Learn More"
    [[params.feature_list.items]]
      image = "images/3-D print.jpg"
	  alt = "3-D print"
      title = "Measurement and 3-D Printing"
      text = "Our tailors then take your measurements with a 3-D camera, a process which takes less than 20 minutes. We then print the 3-D model in order to be able to fit your suit perfectly. This whole process takes less than two days, much faster than a traditional approach."
      button_link = "/faq"
      button_text = "Learn More"
	[[params.feature_list.items]]
      image = "images/Rack of Suits.png"
	  alt = "Rack of Suits"
      title = "Delivery and Precise Measurements"
      text = "Over the course of two weeks, we finish your suit and ship it off to you. Furthermore, if you choose to order more suits, we will not have to take any new measurements because we already have the 3-D model of your body."
      button_link = "/faq"
      button_text = "Learn More"

  [params.gallery]
    title = "Check Out Our Amazing Suits"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["showcase-1.png", "showcase-2.jpg", "showcase-3.jpg", "showcase-4.jpg", "showcase-5.jpg", "showcase-6.jpg", "showcase-7.png", "showcase-8.png"]

  [params.call_to_action]
    title = "Get Suit Updates"
    text = "Stay up to date"
    placeholder = "Your Email Address Here"
    button_text = "Subscribe"

  [params.testimonials]
    title = "Suit Reviews"
    [[params.testimonials.blocks]]
      text = "PLACEHOLDER lots and lots of PLACEHOLDER"
      name = "Placeholder Smith"
      position = "Placeholder, Placeholder Inc"
      image = "images/avatar.png"
	  alt = "Placeholder Smith"
    [[params.testimonials.blocks]]
      text = "PLACEHOLDER lots and lots of PLACEHOLDER"
      name = "Placeholder Smith"
      position = "Placeholder, Placeholder Inc"
      image = "images/avatar.png"
	  alt = "Placeholder Smith"
    [[params.testimonials.blocks]]
      text = "PLACEHOLDER lots and lots of PLACEHOLDER"
      name = "Placeholder Smith"
      position = "Placeholder, Placeholder Inc"
      image = "images/avatar.png"
	  alt = "Placeholder Smith"
    [params.testimonials.button]
      link = "/contact"
      text = "Get Your Suit Now"


	[params.f1]
		title = "Singapore F1 Grand Prix Dressed by John Grace"
		image = "images/F1BW.webp"
		alt = "F1 Show"
		button_text = "Order Your Own Suit Now"
		link = "/contact"
		[[params.f1.images]]
			image = "images/f1-showcase1.webp"
			alt = "F1 Showcase 1"
		[[params.f1.images]]
			image = "images/f1-showcase4.webp"
			alt = "F1 Showcase 4"
		[[params.f1.images]]
			image = "images/f1-showcase3.webp"
			alt = "F1 Showcase 3"
		[[params.f1.images]]
			image = "images/f1-showcase2.webp"
			alt = "F1 Showcase 2"

    [params.suits]
    title = "Suits"
    [[params.suits.suitImages]]
      image = "images/showcase/showcase-1.png"
      alt = "Suit"
    [[params.suits.suitImages]]
      image = "images/showcase/showcase-2.jpg"
      alt = "Suit"
    [[params.suits.suitImages]]
      image = "images/showcase/showcase-3.jpg"
      alt = "Suit"
    [[params.suits.suitImages]]
      image = "images/showcase/showcase-4.jpg"
      alt = "Suit"
    [[params.suits.fittingLining]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/03/slim-fit-final.jpg"
      alt = "Slim Fit"
      text = "Slim Fit"
    [[params.suits.fittingLining]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/03/regular-fit-final.jpg"
      alt = "Regular Fit"
      text = "Regular Fit"
    [[params.suits.construction]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/06/fused.jpg"
      alt = "Fused Jacket"
      text = "Fused Jacket"
    [[params.suits.construction]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/06/half-canvas.jpg"
      alt = "Half-Canvas Jacket"
      text = "Half-Canvas Jacket"
    [[params.suits.construction]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/06/full-canvas.jpg"
      alt = "Full-Canvas Jacket"
      text = "Full-Canvas Jacket"
    [[params.suits.lining]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/04/full-lining.jpg"
      alt = "Full Lining"
      text = "Full Lining"
    [[params.suits.lining]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/04/half-lining.jpg"
      alt = "Half Lining"
      text = "Half Lining"
    [[params.suits.lining]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/04/quarter-lining-1.jpg"
      alt = "Quarter lining"
      text = "Quarter lining"
    [[params.suits.liningColor]]
      image = "https://www.editsuits.com/wp-content/uploads/2016/06/FLL621-003.jpg"
      alt = "Cream"
      text = "Cream"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/04/FLLYKE819-960.jpg"
      alt = "Navy"
      text = "Navy"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/04/FLLYK1780-139.jpg"
      alt = "Burgundy"
      text = "Burgundy"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/06/FLLF502-213.jpg"
      alt = "Pink"
      text = "Pink"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/04/FLL622-BK.jpg"
      alt = "Black"
      text = "Black"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/06/FLLDL014.jpg"
      alt = "Light Blue Paisley"
      text = "Light Blue Paisley"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/06/FLLDL031.jpg"
      alt = "Park Paisley"
      text = "Park Paisley"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/06/FLL0388-810.jpg"
      alt = "Grey Diamonds"
      text = "Grey Diamonds"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/06/FLL7142-5.jpg"
      alt = "Blue Check"
      text = "Blue Check"
    [[params.suits.liningColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/06/FLL86742-1.jpg"
      alt = "Purple Dots"
      text = "Purple Dots"
    [[params.suits.jacketFront]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/156.jpg"
      alt = "Single Breasted - One Button"
      text = "Single Breasted - One Button"
    [[params.suits.jacketFront]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/157.jpg"
      alt = "Single Breasted - Two Buttons"
      text = "Single Breasted - Two Buttons"
    [[params.suits.jacketFront]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/158.jpg"
      alt = "Double Breasted - Six Buttons"
      text = "Double Breasted - Six Buttons"
    [[params.suits.jacketBottom]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/10/front-opening-normal-2.jpg"
      alt = "Regular Front"
      text = "Regular Front"
    [[params.suits.jacketBottom]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/10/front-opening-less-rounded-2.jpg"
      alt = "Less Rounded Front"
      text = "Less Rounded Front"
    [[params.suits.lapel]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/160.jpg"
      alt = "Notched Lapel - Slim (6.4cm)"
      text = "Notched Lapel - Slim (6.4cm)"
    [[params.suits.lapel]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/159.jpg"
      alt = "Notched Lapel - Regular (8.3cm)"
      text = "Notched Lapel - Regular (8.3cm)"
    [[params.suits.lapel]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/161.jpg"
      alt = "Peaked Lapel - Regular (7.3cm)"
      text = "Peaked Lapel - Regular (7.3cm)"
    [[params.suits.lapel]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2016/03/Wide-peak-lapel.jpg"
      alt = "Peaked Lapel - Wide (8.9cm)"
      text = "Peaked Lapel - Wide (8.9cm)"
    [[params.suits.picStitch]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/10/no-pic-stitch.jpg"
      alt = "No Pic Stitch"
      text = "No Pic Stitch"
    [[params.suits.picStitch]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/10/pic-stitch.jpg"
      alt = "Pic Stitch"
      text = "Pic Stitch"
    [[params.suits.jacketPockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/162.jpg"
      alt = "Flap Pockets - Regular"
      text = "Flap Pockets - Regular"
    [[params.suits.jacketPockets]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/11/Flap-Pocket-with-ticket-pocket.jpg"
      alt = "Flap Pockets - Regular, with Ticket Pocket"
      text = "Flap Pockets - Regular, with Ticket Pocket"
    [[params.suits.jacketPockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/163.jpg"
      alt = "Flap Pockets - Slanted"
      text = "Flap Pockets - Slanted"
    [[params.suits.jacketPockets]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/11/Slanted-pocket-with-slanted-ticket-pocket.jpg"
      alt = "Flap Pockets - Slanted, with Ticket Pocket"
      text = "Flap Pockets - Slanted, with Ticket Pocket"
    [[params.suits.jacketPockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/164.jpg"
      alt = "Jetted Pockets - Regular"
      text = "Jetted Pockets - Regular"
    [[params.suits.jacketPockets]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/11/Jetted-Pocket-with-ticket-pocket.jpg"
      alt = "Jetted Pockets - Regular, with Ticket Pocket"
      text = "Jetted Pockets - Regular, with Ticket Pocket"
    [[params.suits.jacketPockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/165.jpg"
      alt = "Patch Pockets"
      text = "Patch Pockets"
    [[params.suits.vents]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/170.jpg"
      alt = "Side Vents"
      text = "Side Vents"
    [[params.suits.vents]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/169.jpg"
      alt = "Center Vent"
      text = "Center Vent"
    [[params.suits.monogram]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/10/DSC_9506.jpg"
      alt = "With Monogram"
      text = "With Monogram"
    [[params.suits.monogram]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/10/no-monogram.jpg"
      alt = "Without Monogram"
      text = "Without Monogram"
    [[params.suits.monogramFont]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/Arial-White.jpg"
      alt = "Sans Serif Font"
      text = "Sans Serif Font"
    [[params.suits.monogramFont]]
      image = "https://www.editsuits.com//wp-content/uploads/2015/03/Calligraphy-White.jpg"
      alt = "Calligraphy Font"
      text = "Calligraphy Font"
    [[params.suits.monogramFont]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/Script-White.jpg"
      alt = "Script Font"
      text = "Script Font"
    [[params.suits.monogramFontColor]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/Arial-White.jpg"
      alt = "White"
      text = "White"
    [[params.suits.monogramFontColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/03/Arial-Grey.jpg"
      alt = "Grey"
      text = "Grey"
    [[params.suits.monogramFontColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/03/Arial-Burgundy.jpg"
      alt = "Burgundy"
      text = "Burgundy"
    [[params.suits.monogramFontColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2014/03/Arial-Navy.jpg"
      alt = "Navy"
      text = "Navy"
    [[params.suits.monogramFontColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/03/Arial-Silver.jpg"
      alt = "Silver"
      text = "Silver"
    [[params.suits.monogramFontColor]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/03/Arial-Gold.jpg"
      alt = "Gold"
      text = "Gold"
    [[params.suits.pantFront]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/205.jpg"
      alt = "No Pleat"
      text = "No Pleat"
    [[params.suits.pantFront]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/206.jpg"
      alt = "One Pleat"
      text = "One Pleat"
    [[params.suits.outerWaistband]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/03/Belt-loop.jpg"
      alt = "Belt Loops"
      text = "Belt Loops"
    [[params.suits.outerWaistband]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2015/03/Side-adjusters.jpg"
      alt = "Side Adjusters"
      text = "Side Adjusters"
    [[params.suits.innerWaistband]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/04/Standard-waistband.jpg"
      alt = "Standard Waistband"
      text = "Standard Waistband"
    [[params.suits.innerWaistband]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/04/Suspender-buttons.jpg"
      alt = "Suspender Buttons Waistband"
      text = "Suspender Buttons Waistband"
    [[params.suits.pantSidePockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/207.jpg"
      alt = "Vertical Pockets"
      text = "Vertical Pockets"
    [[params.suits.pantSidePockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/208.jpg"
      alt = "Slanted Pockets"
      text = "Slanted Pockets"
    [[params.suits.pantBackPockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/211.jpg"
      alt = "Right Pocket With Button"
      text = "Right Pocket With Button"
    [[params.suits.pantBackPockets]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/06/right-back-pocket-no-button.jpg"
      alt = "Right Pocket Without Button"
      text = "Right Pocket Without Button"
    [[params.suits.pantBackPockets]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/212.jpg"
      alt = "Two Pockets With Buttons"
      text = "Two Pockets With Buttons"
    [[params.suits.pantBackPockets]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/06/two-back-pockets-no-buttons.jpg"
      alt = "Two Pockets Without Buttons"
      text = "Two Pockets Without Buttons"
    [[params.suits.pantBackPockets]]
      image = "https://editsuits-ypne1uvwbsy.netdna-ssl.com/wp-content/uploads/2017/06/no-back-pockets.jpg"
      alt = "No Pockets"
      text = "No Pockets"
    [[params.suits.pantHem]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/213.jpg"
      alt = "Without Cuff"
      text = "Without Cuff"
    [[params.suits.pantHem]]
      image = "https://www.editsuits.com//wp-content/uploads/2014/03/214.jpg"
      alt = "With Cuff"
      text = "With Cuff"


	[params.blog]
		date_format = "January 2, 2006"

	[params.widgets]
		categories = true
		tags = true
		search = false

	[Permalinks]
		blog = "/blog/:year/:month/:day/:filename/"

  [params.contact]
	email = "tosha7y@gmail.com"
	address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
	latitude = "-12.043333"
    longitude = "-77.028333"
	googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

  # Footer uses navbar data
